### ISSUE TITLE
Support for central key/CSR generation or Service generation through Venafi TPP

### ISSUE THREAD

**Issue by GeoffVenafi** [Venafi/vcert-python#50]
**BUSINESS PROBLEM**
Most of my customers Certificate solutions use central key/CSR generation. They would like to use vcert-python but this is a blocker for them to deploy to their teams. 

**PROPOSED SOLUTION**
Adding Service Generated Keys/CSRs to vcert-Python

**CURRENT ALTERNATIVES**
Customer is either building the certs manually through Venafi TPP UI and importing the certs manually or using the API to generate and then retrieve the cert then manually install the cert. 

**VENAFI EXPERIENCE**
My customer has been using Venafi for well over a decade and uses Venafi on a daily basis to service their entire certificate inventory.

**Comment by tr1ck3r** [comment]
Thank you @GeoffVenafi Can you please elaborate on the benefit and/or business requirement for service (TPP) generation over local (VCert) generation?  We prioritized local generation because (especially at scale) it is beneficial to offload/distribute the computational overhead of key generation and it adheres to the generally accepted security best practice of storing private keys only where they are used (i.e. with the application server).  We believe it is the optimal fit for the DevOps use cases which are the primary targets of our open source integrations.  We're aware of a couple cases where service generation would be needed but I'll avoid mentioning them until after you have a chance to comment.  Thank you!
