### ISSUE TITLE
TPPTokenConnection not able to customize OAuth scope

### ISSUE THREAD

**Issue by FooBarWidget** [Venafi/vcert-python#54]
**PROBLEM SUMMARY**
TPPTokenConnection always uses the `certificate:manage,revoke;configuration:manage` scope when POSTing to /vedauth/authorize/oauth. This is hardcoded, as opposed to customizable.

On my TPP this causes an authorization issue. I'm not able to authorize with my TPP until I remove the 'configuration:manage' scope.

**COMMENTS/WORKAROUNDS**
TPPTokenConnection's constructor creates an Authentication object with no way to customize its `scope` property. As a result, the Authentication object always uses the default `SCOPE` constant, whose value is `certificate:manage,revoke;configuration:manage`.

**Comment by tr1ck3r** [comment]
This bug was likely introduced with the Certificate Policy Management feature which requires the `configuration:manage` scope.  The default scope required for VCert should have remained `certificate:manage,revoke` since the managing certificate policy is considered an administrative feature (i.e. different persona).  VCert should be providing the ability to override the default scope when getting a new token so that a token can be obtained for Certificate Policy Management.

**Comment by rvelaVenafi** [comment]
The default scope has been reverted to that of certificate management.
If a different scope is required, a new access token must be requested with the given scope.
An example of how to do this has been added to the examples folder.
