### ISSUE TITLE
TPPTokenConnection not able to customize ClientID

### ISSUE THREAD

**Issue by FooBarWidget** [Venafi/vcert-python#55]
TPPTokenConnection always sends `client_id` value equal to `vcert-sdk`. Paul Cleary requested that our products use a different client_id value, for tracking purposes to tell which integrations are seeing the most use in your customer base.

However, TPPTokenConnection does not allow customizing client_id. TPPTokenConnection's constructor creates an Authentication object with only very limited customization options. The client which constructs TPPTokenConnection is not able to customize the Authentication object's client_id option.

**Comment by tr1ck3r** [comment]
It is indeed expected that the VCert consumer may, and almost always will, override the value of `client_id` when requesting a new token because the `client_id` is a unique identifier that represents the API integrated application in Trust Protection Platform for managing access.

**Comment by rvelaVenafi** [comment]
The client_id can be changed by creating a new Authentication object and requesting a new access token.
We added the default client id as convenience for the users.  
A demo has been added to examples folder for this purpose.

The client id has not been exposed to the general Connection object because, at this moment, it does not apply for VaaS platform. When that happens, we can reconsider exposing it as part of the optional Connection arguments.
